"""
계약서류 검토 룰 정의 — 실제 입찰공고문 텍스트 기반 v2
"""
from __future__ import annotations

RULES: list[dict] = [
    # 1. 금액 오탈자 (비정상: "1,40,909,091")
    {
        "id": "R101",
        "category": "typo",
        "severity": "critical",
        "title": "금액 표기 오탈자 (콤마 자릿수 오류)",
        "description": "금액의 천단위 구분 콤마 위치가 잘못되었습니다. '1,40,909,091'처럼 자릿수가 맞지 않습니다.",
        "recommendation": "금액은 3자리마다 콤마로 구분해야 합니다. 예: 1,409,090,909",
        "law_ref": None,
        "check_type": "regex_match",
        "params": {
            "pattern": r"\d{1,3},\d{1,2},\d",
            "violation_condition": "found",
        },
    },
    # 2. 제출서류 항목값 누락
    {
        "id": "R102",
        "category": "missing",
        "severity": "high",
        "title": "제출서류 항목 내용 누락",
        "description": "'제출서류 :' 항목의 내용이 비어있습니다.",
        "recommendation": "제출서류 목록을 구체적으로 기재하거나 '제안요청서 참조' 등으로 명시하세요.",
        "law_ref": None,
        "check_type": "regex_match",
        "params": {
            "pattern": r"제출서류\s*:\s*[\r\n]",
            "violation_condition": "found",
        },
    },
    # 3. 항목 순서 오류
    {
        "id": "R103",
        "category": "inconsistency",
        "severity": "warning",
        "title": "문서 항목 순서 오류",
        "description": "입찰참가자격(3항) 내용이 입찰 및 계약방법(2항)보다 앞에 위치합니다.",
        "recommendation": "표준 양식 순서대로 수정하세요: 1)입찰사항 → 2)계약방법 → 3)참가자격",
        "law_ref": "지방자치단체 입찰 및 계약집행기준",
        "check_type": "order_check",
        "params": {
            "first_keyword":  "3. 입찰참가자격",
            "second_keyword": "2. 입찰 및 계약방법",
        },
    },
    # 4. 사업내용 내용 누락
    {
        "id": "R104",
        "category": "missing",
        "severity": "warning",
        "title": "사업내용 및 설명회 항목 내용 누락",
        "description": "'사업내용 및 설명회 :' 항목의 내용이 없습니다.",
        "recommendation": "'제안요청서 참조(설명회는 제안요청서로 갈음)' 등 내용을 기재하세요.",
        "law_ref": None,
        "check_type": "regex_match",
        "params": {
            "pattern": r"사업내용\s*및\s*설명회\s*:\s*[\r\n]",
            "violation_condition": "found",
        },
    },
    # 5. 기초금액 텍스트-표 불일치
    {
        "id": "R105",
        "category": "inconsistency",
        "severity": "high",
        "title": "기초금액 텍스트-표 금액 불일치",
        "description": "기초금액 텍스트(금일억일천만원=110,000,000)와 표 금액(1,550,000,000)이 일치하지 않습니다.",
        "recommendation": "기초금액 텍스트와 표 숫자를 동일하게 수정하세요.",
        "law_ref": None,
        "check_type": "amount_mismatch",
        "params": {
            "pattern_text_amount":  r"금일억일천만원",
            "pattern_table_amount": r"1,550,000,000",
            "violation_condition": "both_found",
        },
    },
    # 기존 핵심 룰
    {
        "id": "R001",
        "category": "missing",
        "severity": "high",
        "title": "사업명(용역명) 누락",
        "description": "문서에 용역명이 명시되어 있지 않습니다.",
        "recommendation": "1)항에 '용 역 명 :' 항목을 기재하세요.",
        "law_ref": None,
        "check_type": "keyword_missing",
        "params": {"keywords": ["용 역 명", "용역명", "과업명"]},
    },
    {
        "id": "R002",
        "category": "missing",
        "severity": "high",
        "title": "용역기간 누락",
        "description": "문서에 용역기간이 명시되어 있지 않습니다.",
        "recommendation": "용역기간(착수일로부터 N일)을 기재하세요.",
        "law_ref": "지방계약법 시행령 제50조",
        "check_type": "keyword_missing",
        "params": {"keywords": ["용역기간", "착수일로부터"]},
    },
    {
        "id": "R003",
        "category": "missing",
        "severity": "high",
        "title": "기초금액 누락",
        "description": "기초금액이 명시되어 있지 않습니다.",
        "recommendation": "기초금액(부가가치세 포함/별도 여부)을 기재하세요.",
        "law_ref": None,
        "check_type": "keyword_missing",
        "params": {"keywords": ["기초금액"]},
    },
    {
        "id": "R010",
        "category": "regulation_violation",
        "severity": "critical",
        "title": "공동도급 금지 문구 누락",
        "description": "단독이행 의무/공동도급 불허 문구가 없습니다.",
        "recommendation": "'본 용역은 단독이행만 가능합니다.(공동도급은 허용하지 않음.)' 문구를 추가하세요.",
        "law_ref": "지방계약법 시행령 제92조",
        "check_type": "keyword_missing",
        "params": {"keywords": ["단독이행", "공동도급은 불허", "공동도급은 허용하지"]},
    },
    {
        "id": "R011",
        "category": "regulation_violation",
        "severity": "high",
        "title": "입찰보증금 조항 누락",
        "description": "입찰보증금 납부/면제 조항이 없습니다.",
        "recommendation": "입찰보증금 조항(면제 또는 25/1,000 이상)을 명시하세요.",
        "law_ref": "지방계약법 시행령 제37조",
        "check_type": "keyword_missing",
        "params": {"keywords": ["입찰보증금"]},
    },
    {
        "id": "R013",
        "category": "regulation_violation",
        "severity": "high",
        "title": "낙찰하한율(80%) 기준 누락",
        "description": "SW사업 낙찰하한율(100분의 80) 기준이 없습니다.",
        "recommendation": "'사업금액의 100분의 80 미만 배점 감점' 조항을 명시하세요.",
        "law_ref": "소프트웨어진흥법 제48조",
        "check_type": "keyword_missing",
        "params": {"keywords": ["100분의 80", "낙찰하한"]},
    },
    {
        "id": "R030",
        "category": "approval_rule",
        "severity": "info",
        "title": "고액 용역 결재선 안내",
        "description": "1억원 이상 용역으로 국장 이상 결재가 필요합니다.",
        "recommendation": "사무전결규정 확인: 담당 → 팀장 → 과장 → 국장 (→ 구청장)",
        "law_ref": "서초구 사무전결규정",
        "check_type": "amount_threshold",
        "params": {
            "amount_keywords": ["기초금액", "추정금액"],
            "threshold": 100_000_000,
            "violation_condition": "gte",
        },
    },
]